name: Ansible Vault
on: [push]

jobs:
  ansible_vault_job:
    runs-on: ubuntu-latest
    name: Execute Sample secret
    steps:
      - uses: actions/checkout@v1
      - name: Execute secret Action Step
        id: Execution
        uses: DailyVanity/ansible.vault.action@master
        env:
          ANSIBLE_STDOUT_CALLBACK: debug
          ANSIBLE_FORCE_COLOR: true
        with:
          filesToDecrypt: ".ansible/secretFile.txt"
          keyFileVaultPass: secretkeyfortest
